name: Build and Test (.NET 8)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options: [dev, stage, prod]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Verify .NET installation
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore HomePage/HomePage/HomePage.csproj

      - name: Build project
        run: dotnet build HomePage/HomePage/HomePage.csproj --configuration Release --no-restore

      - name: Run Unit Tests (if available)
        shell: pwsh
        run: |
          if (Test-Path "HomePage.Tests/HomePage.Tests.csproj") {
            dotnet test HomePage.Tests/HomePage.Tests.csproj --configuration Release --no-build --verbosity normal
          } else {
            Write-Host "No test project found — skipping test step."
          }

      - name: Publish application
        run: dotnet publish HomePage/HomePage/HomePage.csproj -c Release -o ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: homepage-dotnet8
          path: ./publish
